#Script used to enumerate the URL's generated by the BEPS exploit kits domain generation algorithm.


import socket
import sys

extensions = open('extensions', 'r')
nouns = open('nouns', 'r')
nouns2 = open('nouns', 'r')
bizWord = open('biz', 'r')

extensionList = []
for extension in extensions:
    extensionList.append(extension.rstrip())

nounsList = []
for noun in nouns:
    nounsList.append(noun.rstrip())

bizList = []
for biz in bizWord:
    bizList.append(biz.rstrip())

for biz in bizList:
    for noun in nounsList:
        for noun2 in nounsList:
            for extension in extensionList:
                url = biz.rstrip() + noun.rstrip() + noun2.rstrip() + extension.rstrip()
                try:
                    sys.stdout.write(url + '\r')
                    sys.stdout.flush()
                    theSocket = socket.getaddrinfo(url, 80)
                    print url
                    with open("output.txt", "a") as f:
                        f.write(url + '\n')
                except:
                    pass
print 'fin'